spring.datasource.url=jdbc:postgresql://82.26.150.189:5432/nowme
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=nowme
spring.datasource.password=2LFzrydd2RQxLfT5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
