spring.application.name=NowMe

spring.datasource.url=jdbc:postgresql://82.26.150.189:5432/nowme
spring.datasource.username=nowme
spring.datasource.password=2LFzrydd2RQxLfT5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

server.port=25565